PHASE:=fetch src patch config compile install clean srcclean distclean

.PHONY: all
all: compile

.PHONY: $(PHASE)
$(PHASE):
	@echo placeholder: phase [$@]

src: fetch

patch: src

config: patch

compile: config

install:

srcclean:

distclean:
