name: dev

on:
  push:
    branches:
    - dev
    - 'feature/**'

  pull_request:
    branches:
    - main
    - dev
    - 'feature/**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout self (nix-from-scratch)
      uses: actions/checkout@v4

    - name: install ubuntu dependencies
      run: |
        echo ubuntu-dep-placeholder

    - name: build
      run: |
        echo build-placeholder
