name: main

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout self (nix-from-scratch)
      uses: actions/checkout@v4

    - name: install ubuntu dependencies
      run: |
        PREFIX='${{github.workspace}}/local'
        echo PREFIX=$PREFIX
        echo HOME=$HOME
        echo ubuntu-dep-placeholder

    - name: toplevel config
      run: |
        ./mk/bootstrap.sh --prefix='${{github.workspace}}/local'
        cat mk/prefix.mk

    - name: m4
      run: |
        ./mk/do-github-package-workflow.sh --prefix=$PREFIX --package=m4

    - name: autoconf
      run: |
        ./mk/do-github-package-workflow.sh --prefix=$PREFIX --package=autoconf

    - name: autoconf-archive
      run: |
        ./mk/do-github-package-workflow.sh --prefix=$PREFIX --package=autoconf-archive

    - name: automake
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=automake

    - name: pkgconf
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgconf

    - name: zlib
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=zlib

    - name: flex
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=flex

    - name: bison
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=bison

    - name: openssl
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=openssl

    - name: curl-stage1
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=curl-stage1

    - name: jq
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=jq

    - name: cmake
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=cmake

    - name: libuv
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libuv

    - name: expat
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=expat

    - name: libcpuid
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libcpuid

    - name: editline
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=editline

    - name: patchelf
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=patchelf

    - name: sqlite
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=sqlite

    - name: python
      run: |
        ./mk/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=python
