name: main

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

env:
  BUILD_TYPE: Release

jobs:
  toolchain:
    runs-on: ubuntu-latest

    steps:
      - name: checkout self (nix-from-scratch)
        uses: actions/checkout@v4

      - name: install ubuntu dependencies
        run: |
          PREFIX='${{github.workspace}}/local'
          echo PREFIX=$PREFIX
          echo HOME=$HOME
          echo ubuntu-dep-placeholder

      - name: toplevel config
        run: |
          # replace PREFIX in mk/prefix.mk
          ./scripts/bootstrap.sh --prefix='${{github.workspace}}/local' --nxfs-toolchain-prefix='${{github.workspace}}/nxfs-toolchain'
          cat mk/prefix.mk

# deferring this for now, seems broken on github
#
#      - name: build toolchain (binutils + gcc + glibc)
#        run: |
#          # note: prefix here used in readonly sense, to log summary of toolchain install
#          ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/nxfs-toolchain' --package=toolchain/toolchain

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout self (nix-from-scratch)
      uses: actions/checkout@v4

    - name: install ubuntu dependencies
      run: |
        PREFIX='${{github.workspace}}/local'
        echo PREFIX=$PREFIX
        echo HOME=$HOME
        echo ubuntu-dep-placeholder

    - name: toplevel config
      run: |
        ./scripts/bootstrap.sh --prefix='${{github.workspace}}/local'
        cat mk/prefix.mk

    - name: m4
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/m4

    - name: autoconf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/autoconf

    - name: autoconf-archive
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/autoconf-archive

    - name: automake
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/automake

    - name: pkgconf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/pkgconf

    - name: zlib
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/zlib

    - name: ncurses
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/ncurses

    - name: patchelf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/patchelf

    - name: readline
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/readline

    - name: flex
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/flex

    - name: bison
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/bison

    - name: perl
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/perl

    - name: openssl
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/openssl

    - name: zstd
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/zstd

    - name: curl-stage1
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/curl-stage1

    - name: jq
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/jq

    - name: bzip2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/bzip2

    - name: libarchive
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libarchive

    - name: cmake
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/cmake

    - name: libuv
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libuv

    - name: expat
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/expat

    - name: libcpuid
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libcpuid

    - name: editline
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/editline

    - name: sqlite
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/sqlite

    - name: python
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/python

    - name: libsodium
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libsodium

    - name: libtool
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libtool

    - name: libssh2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libssh2

    - name: bzip2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/bzip2

    - name: pcre
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/pcre

    - name: libgit2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libgit2

    - name: lowdown
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/lowdown

    - name: brotli
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/brotli

    - name: gperf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/gperf

    - name: libseccomp
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/libseccomp

    - name: boost
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/boost

    - name: boehm-gc
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/boehm-gc

    - name: curl-stage2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/curl-stage2

    - name: nlohmann_json
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/nlohmann_json

    - name: gtest
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/gtest

    - name: rapidcheck
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/rapidcheck

    - name: toml11
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/toml11

    - name: unzip
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/unzip

    - name: mdbook-linkcheck
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/mdbook-linkcheck

    - name: mdbook
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/mdbook

    - name: nix
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/nix

    - name: xz
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgs/xz
