name: main

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout self (nix-from-scratch)
      uses: actions/checkout@v4

    - name: install ubuntu dependencies
      run: |
        PREFIX='${{github.workspace}}/local'
        echo PREFIX=$PREFIX
        echo HOME=$HOME
        echo ubuntu-dep-placeholder

    - name: toplevel config
      run: |
        ./scripts/bootstrap.sh --prefix='${{github.workspace}}/local'
        cat mk/prefix.mk

    - name: m4
      run: |
        ./scripts/do-github-package-workflow.sh --prefix=$PREFIX --package=m4

    - name: autoconf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix=$PREFIX --package=autoconf

    - name: autoconf-archive
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=autoconf-archive

    - name: automake
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=automake

    - name: pkgconf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=pkgconf

    - name: zlib
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=zlib

    - name: ncurses
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=ncurses

    - name: readline
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=readline

    - name: flex
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=flex

    - name: bison
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=bison

    - name: perl
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=perl

    - name: openssl
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=openssl

    - name: zstd
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=zstd

    - name: curl-stage1
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=curl-stage1

    - name: jq
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=jq

    - name: libarchive
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libarchive

    - name: cmake
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=cmake

    - name: libuv
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libuv

    - name: expat
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=expat

    - name: libcpuid
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libcpuid

    - name: editline
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=editline

    - name: patchelf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=patchelf

    - name: sqlite
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=sqlite

    - name: python
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=python

    - name: libsodium
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libsodium

    - name: libtool
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libtool

    - name: libssh2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libssh2

    - name: libgit2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libgit2

    - name: lowdown
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=lowdown

    - name: brotli
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=brotli

    - name: gperf
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=gperf

    - name: libseccomp
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=libseccomp

    - name: boost
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=boost

    - name: boehm-gc
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=boehm-gc

    - name: curl-stage2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=curl-stage2

    - name: gtest
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=gtest

    - name: rapidcheck
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=rapidcheck

    - name: toml11
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=toml11

    - name: nix
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=nix

    - name: unzip
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=unzip

    - name: mdbook-linkcheck
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=mdbook-linkcheck

    - name: mdbook
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=mdbook

    - name: bzip2
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=bzip2

    - name: nix
      run: |
        ./scripts/do-github-package-workflow.sh --prefix='${{github.workspace}}/local' --package=nix
